#!/bin/bash

set -e

# Filter out any files with a !golint build tag.
LINTABLE=$( go list -tags=golint -f '
  {{- range $i, $file := .GoFiles -}}
    {{ $file }} {{ end }}
  {{ range $i, $file := .TestGoFiles -}}
    {{ $file }} {{ end }}' github.com/gostores/sincere/oidc )

go test -v -i -race github.com/gostores/sincere/oidc/...
go test -v -race github.com/gostores/sincere/oidc/...
golint -set_exit_status $LINTABLE
go vet github.com/gostores/sincere/oidc/...
go build -v ./example/...
